language: node_js
sudo: false
node_js:
  - '0.10'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - npm install
  - bower install
script: grunt travis
before_deploy:
  - grunt deploy
  - grunt compress
deploy:
  provider: releases
  api_key:
    secure: f7O3qutyiv21MsWcfaWfekyOHgsul6xhSAGFVtvNJ0O5L1q6v4xWi7Dg7+RD6mHnrfgVUqYnx1CAmnsL2bubqNZhqAWrA+yGEs4BCTCqRNyhmGans0TwUSLauDRRKWYDGBT6488oY1OoAsL7U0BomHbGqRz4lZkTbgywzjUnRd8=
  file: "dist/angular-summernote.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: summernote/angular-summernote
